name: Build & Deploy to GCP

on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
    inputs:
      GCR:
        required: true
        type: string
      PROJECT_ID:
        required: true
        type: string
      GKE_NAME:
        required: true
        type: string
      GKE_LOCATION:
        required: true
        type: string
      GCR_PROJECT_ID:
        required: true
        type: string
      BUILD_CONTEXT:
        required: true
        type: string


jobs:
  deploy-to-gcp:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@master 

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: get gke credentials
      id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ inputs.GKE_NAME }}
        location: ${{ inputs.GKE_LOCATION }}
        project_id: ${{ inputs.PROJECT_ID }}

    - name: Deploy to K8S
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ${{ github.workspace }}/${{ inputs.BUILD_CONTEXT }}/manifests/manifests.yaml
        images: |
          ${{ inputs.GCR }}/${{ inputs.PROJECT_ID }}/${{ github.repository }}/${{ inputs.BUILD_CONTEXT }}:prod-${{ github.sha }}
        namespace: app
