name: Build & Deploy beta Seller to Azure

on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
      GCR:
        required: true
      PROJECT_ID:
        required: true
      GKE_NAME:
        required: true
      GKE_LOCATION:
        required: true


jobs:

  build-push-gcr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: "8"
        distribution: "adopt"
        
    - name: Run mvn clean install
      run: mvn -s mvn-settings.xml clean install -DskipTests  


    - name: Login to GCR
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.GCR }}
        username:  _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}

    - name: Build and Push
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: |
          ${{ secrets.GCR }}/${{ secrets.PROJECT_ID }}/${{ github.repository }}:beta-${{ github.sha }}
          ${{ secrets.GCR }}/${{ secrets.PROJECT_ID }}/${{ github.repository }}:latest

  deploy-to-gcp:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-push-gcr]
    steps:
    - name: checkout
      uses: actions/checkout@master 

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: get gke credentials
      id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_NAME }}
        location: ${{ secrets.GKE_LOCATION }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Deploy to K8S
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ${{ github.workspace }}/manifests/manifests.yaml
        images: |
          ${{ secrets.GCR }}/${{ secrets.PROJECT_ID }}/${{ github.repository }}:beta-${{ github.sha }}
        namespace: app