name: Build & Deploy to GCP

on:
  workflow_call:
    secrets:
      AWS_COM_BUILD_DEPLOY_KEY_ID:
        required: true
      AWS_COM_BUILD_DEPLOY_SECRET_ACCESS_KEY:
        required: true
    inputs:
      AWS_REGION:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      EKS_NAME:
        required: true
        type: string



jobs:

  build-push-ecr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_COM_BUILD_DEPLOY_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_COM_BUILD_DEPLOY_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"
        
    - name: Run mvn clean install
      run: mvn -s mvn-settings.xml clean install -DskipTests  


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Build and Push
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:beta-${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

  deploy-to-eks:
    name: Deploy to eks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-push-ecr]
    steps:
    - name: checkout
      uses: actions/checkout@master 

    - name: Get kubeconfig
      uses: giboow/action-aws-cli@v1
      with:
        args: eks update-kubeconfig --region ${{ inputs.AWS_REGION }} --name ${{ inputs.EKS_NAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_COM_BUILD_DEPLOY_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_COM_BUILD_DEPLOY_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION }}

    - name: Deploy to EKS
      uses: azure/k8s-deploy@v1.2
      with:
        manifests: |
          ${{ github.workspace }}/manifests/manifests.yaml
        images: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:beta-${{ github.sha }}
        namespace: app