name: Build & Deploy GCP

on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
    inputs:
      GCR:
        required: true
        type: string
      PROJECT_ID:
        required: true
        type: string
      GKE_NAME:
        required: true
        type: string
      GKE_LOCATION:
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string
      MODULE:
        required: true
        type: string
      ENV:
        required: false
        type: string
        default: 'dev'
      # MANIFESTS:
      #   required: false
      #   type: string
      #   default: 'manifests.yaml'
      MVN_ARGS:
        required: false
        type: string
        default: ''

jobs:

  build-push-gcr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: "17"
        distribution: "adopt"

    - name: "获取当时的时间"
      id: timestamp
      env:
        TZ: Asia/Shanghai  # 中国时区‌:ml-citation{ref="4" data="citationList"}
      run: |
        echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

    - name: Run mvn clean install
      run: mvn -U -s mvn-settings.xml clean install -DskipTests -ntp ${{ inputs.MVN_ARGS }}

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.GCR }}
        username:  _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}

    - name: Build and Push
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        context: ./${{ inputs.MODULE }}
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: |
          ${{ inputs.GCR }}/${{ inputs.PROJECT_ID }}/${{ github.repository }}/${{ inputs.MODULE }}:${{ inputs.ENV }}-${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}
          ${{ inputs.GCR }}/${{ inputs.PROJECT_ID }}/${{ github.repository }}/${{ inputs.MODULE }}:latest
    outputs:
      image_tag: ${{ inputs.ENV }}-${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}

  deploy-to-gcp:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build-push-gcr]
    steps:
    - name: checkout
      uses: actions/checkout@master

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: get gke credentials
      id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ inputs.GKE_NAME }}
        location: ${{ inputs.GKE_LOCATION }}
        project_id: ${{ inputs.PROJECT_ID }}

    - name: Deploy to K8S
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ${{ github.workspace }}/${{ inputs.MODULE }}/manifests/manifests-${{ inputs.ENV }}.yaml
        images: |
          ${{ inputs.GCR }}/${{ inputs.PROJECT_ID }}/${{ github.repository }}/${{ inputs.MODULE }}:${{ needs.build-push-gcr.outputs.image_tag }}
        namespace: ${{ inputs.NAMESPACE }}
