name: Build & release maven repository

on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
    inputs:
      GCR:
        required: true
        type: string
      PROJECT_ID:
        required: true
        type: string
      GKE_NAME:
        required: true
        type: string
      GKE_LOCATION:
        required: true
        type: string
      namespace:
        required: true
        type: string

jobs:

  build-release-maven-repository:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: "17"
        distribution: "adopt"

    - name: Run mvn clean install
      run: mvn -U -s mvn-settings.xml clean install source:jar deploy -DskipTests -ntp
